grupo-rovema-new/sap-sql-sovis

src/transactions/SBO_SP_TransactionNotification_Rovema.sql
TRAVA BLOQUEIO DE CANCELAMENTO CASO A NF ESTEJA AUTORIZADA, APLICADA NAS ROTINAS ABAIXO: NOTAS DE SAIDA
NF DE ENTREGA FUTURA
DEV. NOTA FISCAL DE SAIDA
ENTREGA
NOTA DE NETRADA
NF RECEBIMENTO FUTURO
RECEBIMENTO DE MERCADORIA
DEVOLUÇÃO DE MERCADORIA
DEV. NOTA FISCAL DE ENTRADA
RETORNO DA TRAVA REFERENTE AO MODELO DE NOTA 55
=> Adição de Novas Travas

src/views/util/QUANTIDADETOTALOINM.sql
Foi formatada o script em CTE (CTEs para dividir a lógica em partes mais gerenciáveis e reutilizáveis, o que pode melhorar a legibilidade e a manutenção.)
Adicionado o campo Nota Fiscal na view
Foi ajustado o campo quantidade que estava trazendo valor zerado em algumas movimentações, principalmente de grãos.
=> Alteração de view QUANTIDADETOTALOINM

src/views/util/FATURAQTDE.sql
Criação da view para uso no Power BI
=> Criacao View

src/transactions/SBO_SP_TransactionNotification_Rovema.sql
Trava de cancelamento permitindo outros status que não deveriam passar.
=> Ajuste Trava

src/views/sovis/TITULOANOTACAO.sql
Foi ajustado a view para que ela siga os mesmo critérios da view TITULO
=> Ajuste TituloAnotação

src/views/sovis/TITULO.sql
Alterado a condição do DocStatus de O, para O e D
=> Alteração view titulo

src/views/util/NOTASENTRADA.sql
View para uso no relatorio Notas de Entrada
=> VIEW NOTAS DE ENTRADA

src/views/util/RELATORIOCOMISSAO.sql
Feito o ajuste da view do relatorio de comissões, para aparecer os adiantamentos vinculados nas notas de entrega futura
=> Alteração RELATORIOCOMISSAO

src/transactions/SBO_SP_TransactionNotification_Katrid.sql
transformou o get dos itens numa consulta
=> alteração transaction katrid

src/transactions/SBO_SP_TransactionNotification.sql, src/transactions/SBO_SP_TransactionNotification_Rovema.sql
Ativação da trava de nota fiscal de saída, criação de trava numeração de ct-e utilizada
=> Atualizações Travas

src/functions/Get_Pedido_Venda_Permissao_Faturamento.sql
Função que valida o saldo dos pedidos de venda para que não gere notas a mais que o combinado.
=> Função validação de saldo pedido de venda

src/transactions/SBO_SP_TransactionNotification.sql
Foi comentada a trava da nota fiscal de saida
=> comentar trava nf saida

src/transactions/SBO_SP_TransactionNotification_Rovema.sql
ajuste na trava de cancelamento do ct-e
=> Ajuste trava CT-e

src/transactions/SBO_SP_TransactionNotification_Rovema.sql
O parceiro é um Produtor Rural, portanto é necessário que o campo "Sujeito IRF" esteja marcado como SIM
=> Trava Campo IRF

src/transactions/SBO_SP_TransactionNotification_Katrid.sql
adicionado a rotina de recebimento, ajuste do objeto da entrega e adicionado o object type de transferencia do deposito
=> Transaction Katrid

src/transactions/SBO_SP_TransactionNotification_Rovema.sql
alteração da mensagem da trava campos codigo de imposto.
=> Trava Alteração campos imposto

src/functions/Get_Pedido_Venda_Permissao_Faturamento.sql, src/transactions/SBO_SP_TransactionNotification.sql
Trava do pedido, quantidade maior que o pedido
=> Transaction e Function Trava

src/functions/Get_Pedido_Venda_Permissao_Faturamento.sql, src/transactions/SBO_SP_TransactionNotification.sql
=> Trans funcion trava

src/transactions/SBO_SP_TransactionNotification.sql
=> Trava Frete Paulo

src/transactions/SBO_SP_TransactionNotification.sql
=> Trava frete

src/transactions/SBO_SP_TransactionNotification.sql
=> Travafretesintaxe

src/views/util/RELATORIOCOMISSAO.sql
Adicionada a condição T6."DocEntry" IS NULL, para só trazer as notas que não referenciadas (devolução).
=> Notas referneciadas

src/transactions/SBO_SP_TransactionNotification_Katrid.sql
correção do nome do objeto referente a rotina de recebimento de mercadoria
=> Trava Katrid

src/transactions/SBO_SP_TransactionNotification_Katrid.sql
Adição do modulo colaboradores, na procedure TransactionNotification_Katrid.
=> Modulo Colaboradores

src/transactions/SBO_SP_TransactionNotification.sql
como as atualizações do consultor está sendo feita direta no banco, estamos atualizando a transaction notification do repositorio do git hub
=> atualização transaction notification

src/transactions/SBO_SP_TransactionNotification.sql
ADIÇÃO DO REPLACE NO ARQUIVO TRANSACTIONNOTIFICATION
=> Transac notification

src/views/financeiro/CR_ValorPago.sql, src/views/financeiro/NFS_FATURADO.sql
Criação de views para o relatorio de comissão de representante
=> Criação Views

src/views/financeiro/NFS_FRETE.sql
View para uso no relatorio comissões representante
=> View Frete NF

src/views/financeiro/CR_TITULOSDESDOBRADO.sql, src/views/financeiro/CR_ValorPago.sql, src/views/financeiro/NFS_COMISSOESTITULOS.sql, src/views/financeiro/NFS_FRETE.sql
views para uso do relatorio de comissões
=> views rel comissões

src/views/financeiro/NFS_COMISSOESTITULOS.sql
=> ajuste view

src/views/financeiro/CR_ValorPago.sql
adicionado mais um select para que puxe os titulo de adiantamento
=> alteração valor pago

src/views/financeiro/CR_TITULOSDESDOBRADO.sql, src/views/financeiro/NFS_COMISSOESTITULOS.sql, src/views/financeiro/NFS_FATURADO.sql, src/views/financeiro/NFS_VALORBRUTO.sql
Foi adicionado um union da tabela odpi de adiantamento de cliente, para que ela apareça no relatorio
=> UNION'S REL COMISSÃO

src/transactions/SBO_SP_TransactionNotification_Katrid.sql
=> correção procedure katrid

src/views/financeiro/CR_TITULOSDESDOBRADO.sql, src/views/financeiro/CR_ValorPago.sql, src/views/financeiro/NFS_FATURADO.sql
Atualizações das views titulos desdobrados, nfs_faturado e valor pago
=> Atualizações Views

src/views/financeiro/NFS_FRETE.sql
Foi adicionado um select de adiantamento do cliente, para trazer os calculos de frete
=> Adição Adiantamento Cliente

src/views/financeiro/NFS_FRETE.sql
Ajuste no script de adiantamento
=> Atualização Frete

src/views/financeiro/NFS_FRETE.sql
Foi ajustado os valores dos titulos que tinha devolução parcial, para que faça o calculo certo.
=> Ajuste Devolução

src/views/financeiro/NFS_FRETE.sql
Colocar o campo de valor de devolução, na view
=> Adicionar o campo Devolução

src/views/financeiro/NFS_FRETE.sql
Adição de uma condição no case quando o desdobramento for maior que 1 e a proporção for diferente de 100
=> Frete201224

src/views/financeiro/CR_ValorPago.sql
Adição dos campos na view CR_VALORPAGO
* Excluido os campos **T1."PaidSum"**, **T1."AppliedSys"**, para trazer mais performace no processamento da view
* TIPO identificar qual é o tipo do titulo pago
* Adicionado a condição **T0."DocType" = 'I'**, para trazer somente pedidos de venda de itens
* Alterado a Formula do Total Pago, para o campo **T12."DrawnSum"**, No select do adiantamento
* Foi adicionado a condição **T0."DpmAmnt" > 0** para trazer valores de adiantamento acima de zero, No select do adiantamento
* Adicionado a condição **T0."DocTotal" = 0**, junto com a condição **T0."DpmAmnt" > 0** para trazer somente adiantamento certos com valores integrais.
=> Atualização CR_VALORPAGO

src/views/financeiro/NFS_FRETE.sql, src/views/financeiro/NFS_PAGTOCOMISSAO.sql
Foi atualizado a View NFS_FRETE, e criado a View NFS_PAGTOCOMISSAO NFS_FRETE: Foi criado um novo calculo "TotPgSFrete4", para corrigir o erro de calculo do chamado do GLPI 9091. NFS_PAGTOCOMISSAO: Foi criado uma nova condição no case para que o calculo "TotPgSFrete4" funcione no relatório
=> Criação e Atualização de View

src/views/sovis/TITULO.sql
Feito ajuste na view no campo "DATAHORAPAGAMENTO" para que mostre o titulos vencidos e os a vencer
=> View TITULO SOVIS

src/views/financeiro/CR_ValorPago.sql, src/views/financeiro/NFS_FRETE.sql, src/views/sovis/TITULO.sql
Atualização de views de comissão, ligação das linenum entre tabelas, view sovis titulos, condição para trazer somente titulos sem data de pagamento
=> Atualização Views

src/views/financeiro/CR_ValorPago.sql, src/views/financeiro/NFS_FRETE.sql, src/views/financeiro/NFS_PAGTOCOMISSAO.sql, src/views/sovis/TITULO.sql
Correção de sintaxe da view src/views/financeiro/NFS_PAGTOCOMISSAO.sql
Correção das ligações entre tabelas e views, pelo campo linenum
Ajuste da formula da comissão do adiantamento nota fiscal
=> View comissao titulos

src/transactions/GetCommentDoc.sql, src/views/util/OBSSAIDA.sql
A release trata de uma melhoria no campo de informações adicionais da nota fiscal, permitindo agora a visualização do vendedor responsável pela emissão.
Para uma melhor visualização do nome do vendedor, será necessário realizar ajustes nos nomes dos vendedores que contêm apenas o primeiro nome, tarefa que ficará a cargo do time comercial.
Foi criada uma view para a visualização dos campos Observação (OBS), DocEntry e ObjType, e a procedure GetCommentDoc foi atualizada, incluindo as informações da view criada.
=> Atualização de View e Procedure Nome do Vendedor na Observação da nota

src/views/util/OBSENTREGA.sql
View OBSENTREGA, que adiciona o nome do vendedor na observação da nota de entrega
=> Criação da View OBSENTREGA

src/views/util/OBSENTREGA.sql
Foi corrigido a descrição da view OBSENTREGA, de SBOGRUPOROVEMA.OBSENTREGA para OBSENTREGA
=> View obsentrega090425

src/transactions/SBO_SP_TransactionNotification_Rovema.sql, src/views/financeiro/NFS_FRETE.sql, src/views/financeiro/NFS_PAGTOCOMISSAO.sql
Adicionado a utilização 67 - venda soja, na trava Troca para Deposito.
Atualização das Views NFS_FRETE, NFS_PAGTOCOMISSAO, parta solução do problemas dos relatorio
=> Atualização de Transaction e Views

src/views/diretoria/Faturamento.sql
Feito o ajuste na linha de frete, para trazer o frete por linha
=> Update View Faturamento
